name: StorageMechanics
version: '${project.version}'
main: wuason.storagemechanics.Storage
api-version: 1.16
softdepend:
  - ItemsAdder
  - Oraxen
  - WorldGuard
  - ChestSort
  - MythicMobs
authors:
  - Wuason
description: Adds storage at blocks or furnitures
website: techmc.es
load: POSTWORLD