name: StorageMechanics
version: '${project.version}'
main: wuason.storagemechanics.Storage
api-version: 1.16
depend:
  - ItemsAdder
softdepend:
  - WorldGuard
authors: [ Wuason ]
description: none
website: techmc.es
load: STARTUP
commands:
  storagemechanics:
    permission: storage.admin
    aliases:
      - sm
      - storagesm